### YamlMime:ManagedReference
items:
- uid: System.Data.Linq.DuplicateKeyException
  id: DuplicateKeyException
  children:
  - System.Data.Linq.DuplicateKeyException.#ctor(System.Object)
  - System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)
  - System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)
  - System.Data.Linq.DuplicateKeyException.Object
  langs:
  - csharp
  name: DuplicateKeyException
  nameWithType: DuplicateKeyException
  fullName: System.Data.Linq.DuplicateKeyException
  type: Class
  summary: "Gerada quando é feita uma tentativa de adicionar um objeto no cache de identidade usando uma chave que já está sendo usada."
  syntax:
    content: 'public class DuplicateKeyException : InvalidOperationException'
  inheritance:
  - System.InvalidOperationException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object)
  id: '#ctor(System.Object)'
  parent: System.Data.Linq.DuplicateKeyException
  langs:
  - csharp
  name: DuplicateKeyException(Object)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Data.Linq.DuplicateKeyException&quot;> </xref> classe."
  syntax:
    content: public DuplicateKeyException (object duplicate);
    parameters:
    - id: duplicate
      type: System.Object
      description: "A chave duplicada que causou a exceção seja lançada."
  overload: System.Data.Linq.DuplicateKeyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)
  id: '#ctor(System.Object,System.String)'
  parent: System.Data.Linq.DuplicateKeyException
  langs:
  - csharp
  name: DuplicateKeyException(Object,String)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Data.Linq.DuplicateKeyException&quot;> </xref> classe fazendo referência a chave duplicada e fornecendo uma mensagem de erro."
  syntax:
    content: public DuplicateKeyException (object duplicate, string message);
    parameters:
    - id: duplicate
      type: System.Object
      description: "A chave duplicada que causou a exceção seja lançada."
    - id: message
      type: System.String
      description: "A mensagem exibida quando a exceção é gerada."
  overload: System.Data.Linq.DuplicateKeyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)
  id: '#ctor(System.Object,System.String,System.Exception)'
  parent: System.Data.Linq.DuplicateKeyException
  langs:
  - csharp
  name: DuplicateKeyException(Object,String,Exception)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String,Exception)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String,Exception)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Data.Linq.DuplicateKeyException&quot;> </xref> classe referenciando a chave duplicada, fornecendo uma mensagem de erro e especificando a exceção que provocou essa exceção seja lançada."
  syntax:
    content: public DuplicateKeyException (object duplicate, string message, Exception innerException);
    parameters:
    - id: duplicate
      type: System.Object
      description: "A chave duplicada que causou a exceção seja lançada."
    - id: message
      type: System.String
      description: "A mensagem exibida quando a exceção é gerada."
    - id: innerException
      type: System.Exception
      description: "A exceção anterior que causou o <xref href=&quot;System.Data.Linq.DuplicateKeyException&quot;> </xref> exceção seja lançada."
  overload: System.Data.Linq.DuplicateKeyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.DuplicateKeyException.Object
  id: Object
  parent: System.Data.Linq.DuplicateKeyException
  langs:
  - csharp
  name: Object
  nameWithType: DuplicateKeyException.Object
  fullName: System.Data.Linq.DuplicateKeyException.Object
  type: Property
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Obtém o objeto que causou a exceção."
  syntax:
    content: public object Object { get; }
    return:
      type: System.Object
      description: "O objeto que causou a exceção."
  overload: System.Data.Linq.DuplicateKeyException.Object*
  exceptions: []
  platform:
  - net462
references:
- uid: System.InvalidOperationException
  isExternal: false
  name: System.InvalidOperationException
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object)
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: DuplicateKeyException(Object)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: DuplicateKeyException(Object,String)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: DuplicateKeyException(Object,String,Exception)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String,Exception)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Data.Linq.DuplicateKeyException.Object
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: Object
  nameWithType: DuplicateKeyException.Object
  fullName: System.Data.Linq.DuplicateKeyException.Object
- uid: System.Data.Linq.DuplicateKeyException.#ctor*
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: DuplicateKeyException
  nameWithType: DuplicateKeyException.DuplicateKeyException
- uid: System.Data.Linq.DuplicateKeyException.Object*
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: Object
  nameWithType: DuplicateKeyException.Object
