### YamlMime:ManagedReference
items:
- uid: System.Web.Query.Dynamic.ParseException
  id: ParseException
  children:
  - System.Web.Query.Dynamic.ParseException.#ctor(System.String,System.Int32)
  - System.Web.Query.Dynamic.ParseException.Position
  - System.Web.Query.Dynamic.ParseException.ToString
  langs:
  - csharp
  name: ParseException
  nameWithType: ParseException
  fullName: System.Web.Query.Dynamic.ParseException
  type: Class
  summary: "Representa erros que ocorrem quando um <xref href=&quot;System.Web.UI.WebControls.LinqDataSource&quot;> </xref> controle analisa os valores para criar uma consulta."
  remarks: "O objeto ParseException contém informações sobre exceções que ocorrem quando o <xref:System.Web.UI.WebControls.LinqDataSource>controle analisa os valores para criar dinamicamente uma consulta.</xref:System.Web.UI.WebControls.LinqDataSource>       Se o <xref:System.Web.UI.WebControls.LinqDataSource.Select%2A>propriedade inclui uma propriedade que não está no objeto de dados, o <xref:System.Web.UI.WebControls.LinqDataSource>controle gera uma exceção ParseException.</xref:System.Web.UI.WebControls.LinqDataSource> </xref:System.Web.UI.WebControls.LinqDataSource.Select%2A> A mensagem indica que a propriedade não existe no objeto de dados.       Você pode atribuir o objeto de dados no <xref:System.Web.UI.WebControls.LinqDataSource.Selecting>evento definindo o <xref:System.Web.UI.WebControls.LinqDataSourceSelectEventArgs.Result%2A>propriedade a um objeto que é retornado de uma consulta.</xref:System.Web.UI.WebControls.LinqDataSourceSelectEventArgs.Result%2A> </xref:System.Web.UI.WebControls.LinqDataSource.Selecting> Se você selecionar uma propriedade que não existe no objeto de dados, o <xref:System.Web.UI.WebControls.LinqDataSource>controle gera uma exceção ParseException.</xref:System.Web.UI.WebControls.LinqDataSource> A mensagem indica que a propriedade particular não existe em um `AnonymousType` objeto."
  syntax:
    content: 'public class ParseException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Query.Dynamic.ParseException.#ctor(System.String,System.Int32)
  id: '#ctor(System.String,System.Int32)'
  parent: System.Web.Query.Dynamic.ParseException
  langs:
  - csharp
  name: ParseException(String,Int32)
  nameWithType: ParseException.ParseException(String,Int32)
  fullName: System.Web.Query.Dynamic.ParseException.ParseException(String,Int32)
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Query.Dynamic
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Web.Query.Dynamic.ParseException&quot;> </xref> classe."
  syntax:
    content: public ParseException (string message, int position);
    parameters:
    - id: message
      type: System.String
      description: "A mensagem que descreve o erro."
    - id: position
      type: System.Int32
      description: "O local do erro."
  overload: System.Web.Query.Dynamic.ParseException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Query.Dynamic.ParseException.Position
  id: Position
  parent: System.Web.Query.Dynamic.ParseException
  langs:
  - csharp
  name: Position
  nameWithType: ParseException.Position
  fullName: System.Web.Query.Dynamic.ParseException.Position
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Query.Dynamic
  summary: "Obtém o local do erro."
  syntax:
    content: public int Position { get; }
    return:
      type: System.Int32
      description: "O local onde ocorreu a exceção."
  overload: System.Web.Query.Dynamic.ParseException.Position*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Query.Dynamic.ParseException.ToString
  id: ToString
  parent: System.Web.Query.Dynamic.ParseException
  langs:
  - csharp
  name: ToString()
  nameWithType: ParseException.ToString()
  fullName: System.Web.Query.Dynamic.ParseException.ToString()
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Query.Dynamic
  summary: "Retorna a mensagem de erro e o local do erro."
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "A mensagem e a posição do erro."
  overload: System.Web.Query.Dynamic.ParseException.ToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Web.Query.Dynamic.ParseException.#ctor(System.String,System.Int32)
  parent: System.Web.Query.Dynamic.ParseException
  isExternal: false
  name: ParseException(String,Int32)
  nameWithType: ParseException.ParseException(String,Int32)
  fullName: System.Web.Query.Dynamic.ParseException.ParseException(String,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Query.Dynamic.ParseException.Position
  parent: System.Web.Query.Dynamic.ParseException
  isExternal: false
  name: Position
  nameWithType: ParseException.Position
  fullName: System.Web.Query.Dynamic.ParseException.Position
- uid: System.Web.Query.Dynamic.ParseException.ToString
  parent: System.Web.Query.Dynamic.ParseException
  isExternal: false
  name: ToString()
  nameWithType: ParseException.ToString()
  fullName: System.Web.Query.Dynamic.ParseException.ToString()
- uid: System.Web.Query.Dynamic.ParseException.#ctor*
  parent: System.Web.Query.Dynamic.ParseException
  isExternal: false
  name: ParseException
  nameWithType: ParseException.ParseException
- uid: System.Web.Query.Dynamic.ParseException.Position*
  parent: System.Web.Query.Dynamic.ParseException
  isExternal: false
  name: Position
  nameWithType: ParseException.Position
- uid: System.Web.Query.Dynamic.ParseException.ToString*
  parent: System.Web.Query.Dynamic.ParseException
  isExternal: false
  name: ToString
  nameWithType: ParseException.ToString
